services:
  app_php:
    image: php:8.3-fpm
    container_name: app_php
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ${PROJECT_SOURCE}:/var/www/html
    depends_on:
      - mysql

    networks:
      backend:
        aliases:
          - app_php

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ${PROJECT_SOURCE}:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx/cache:/var/cache/nginx
      - ./data/nginx/logs:/var/log/nginx
      - ./data/nginx/run:/var/run
    environment:
      - NGINX_USER=www-data
    user: "${UID}:${GID}"
    depends_on:
      - app_php
    networks:
      backend:
        aliases:
          - app_php

  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQLDATA_PATH}:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - backend
networks:
  backend:
    driver: bridge